# https://taskfile.dev

version: "3"

vars:
  PROJECT_ROOT:
    sh: "echo -n $PWD"
  SOURCE_PATH: "{{.PROJECT_ROOT}}/site"
  CONFIG_PATH: "{{.PROJECT_ROOT}}/site"
  CONTENT_PATH: "{{.PROJECT_ROOT}}/site/content"
  OUTPUT_PATH: "{{.PROJECT_ROOT}}/out"
  RESOURCES_PATH: "{{.SOURCE_PATH}}/resources"
  ASSETS_LOCAL_PATH: "{{.PROJECT_ROOT}}/site/assets"
  ASSETS_REMOTE_PATH: "s3://assets.jxf.me"

tasks:
  clean:
    desc: "remove temporary paths"
    cmds:
      - rm -rf {{.OUTPUT_PATH}}
      - rm -rf {{.RESOURCES_PATH}}

  "sync:up":
    desc: "sync assets up to cloud"
    cmds:
      - echo "TODO: not yet implemented"
      - |-
        aws s3 sync --dryrun {{.ASSETS_LOCAL_PATH}} {{.ASSETS_REMOTE_PATH}} \
          --exclude "*" \
          --include "*.png" \
          --include "*.jpeg" \ ..."
  "sync:down":
    desc: "sync assets down to local environment"
    cmds:
      - echo 'TODO: not yet implemented'
      - aws s3 sync --dryrun {{.ASSETS_REMOTE_PATH}} {{.ASSETS_LOCAL_PATH}}

  serve:
    desc: "serve website on a local webserver"
    deps: [clean]
    cmds:
      - |-
        hugo serve \
          --source {{.SOURCE_PATH}} \
          --destination {{.OUTPUT_PATH}}

  build:
    desc: "build the webiste and save it"
    deps: [clean]
    cmds:
      - |-
        hugo \
          --source {{.SOURCE_PATH}} \
          --destination {{.OUTPUT_PATH}}

  new-post:
    desc: "add a new post (with ITEM_NAME=...)"
    preconditions:
      # Don't proceed if the name is blank.
      - test -n "$ITEM_NAME"
    cmds:
      - mkdir -p {{.CONTENT_PATH}}
      - |-
        hugo new -k post {{.ITEM_NAME}} \
          --source {{.PROJECT_ROOT}}/site
